name: rutgers
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bokeh
  - colorcet
  - datashader
  - dask
  - geoviews
  - gh
  - holoviews
  - hvplot
  - jupyter
  - jupyterlab
  - lumen
  - matplotlib
  - networkx
  - nomkl
  - numba
  - numpy
  - pandas
  - param
  - plotly
  - pygithub
  - panel
  - scipy
  - scikit-learn
  - seaborn
  - pyyaml
  - pip
  - pip:
    - contest