name: base
channels:
  - conda-forge
dependencies:
  - bokeh
  - colorcet
  - datashader
  - geopandas=1.0.1
  - geoviews=1.12.0
  - holoviews=1.19.1
  - hvplot
  - jupyter
  - jupyter_bokeh=4.0.5
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - pandas
  - panel=1.4.5
  - plotly
  - scipy
  - scikit-learn
  - streamz
  - pyyaml
  - pip
  - pip:
    - contest
