name: rutgers
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bokeh
  - colorcet
  - datashader
  - geopandas=0.14.1
  - geoviews=1.11.0
  - gh
  - holoviews=1.18.1
  - hvplot
  - jupyter
  - jupyter_bokeh=3.0.7
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - pandas
  - panel=1.3.1
  - plotly
  - pygithub
  - scipy
  - scikit-learn
  - pyyaml
  - pip
  - pip:
    - contest
